<h1 style="text-align:center;">Workshop Training</h1> 

<h2 style="text-align:center;">LULC Analysis and Classification using Remote Sensing Data with Machine Learning Approach</h2> 

### Section 1: Python CrashCourse

Run first python code by press Shift+Enter

In [1]:
print("First Python Run!!")

First Python Run!!


We can document the code to explain what the code does and explain some theory about the code

__Double Click Me!!__ 

Try to Write Markdown Here

You can write _Italic_, __bold__, <span style="color:blue">*Colored*</span>.

Markdown text describing something including ภาษาไทย

# Defining Heading 1
## Defining Heading 2
### Defining Heading 3

- List 1
- List 2
  - List 2.1


Write somthing here...

Latest cell ran single text string to show in output. Now, declare a variable to store some text inside and print it using variable names.

In [3]:
print("This is a string data") # print simple string

some_string = "This is another string data" # store text in variable
some_number = 345 # store number in variable

print(some_string) # print data in string variable

print(some_number) # print data in number variable

This is a string data
This is another string data
345


To print out message including mixing text and number, there are several ways

In [4]:
print("This is a string data" + " and another string data") # concat string by +

print("Print by normal message", some_number, some_string) # concat message by comma -> x,y,z,..

print(f"Print by format string message {some_number} with {some_number}") # format printting using {x} to show data in blacket placement


This is a string data and another string data
Print by normal message 345 This is another string data
Print by format string message 345 with 345


Explore some simple programmatically math calculations to explore __Arithmetic Operation__

In [5]:
print('General Operator')

# General Arithmetic Operators
print(2+3) # Add
print(5-1) # Subtract
print(5*4) # Multiply
print(18/4) # Divide

print('\nAdditional Operator')

# Addditional Arithmetic Operators
print(10//3) # Floor division
print(10%3) # Modulus
print(4**2) # Expotentiation (Power)

General Operator
5
4
20
4.5

Additional Operator
3
1
16


Do some math calculation using those arithmetic operators

In [6]:
# Learn Variables by Linear Algebra

# y = mx+c

m = 3
x = 5
c = 1

y = m * x +c

print(f"The y is: {y}")

The y is: 16


You may know what Fx (Function) in math. Now, try to create a function doing calculation that equation. We do same way as declaring a variable and put the formula like

$$
  f(x) = 5x + 7
$$

explore how to write Latex formula at <a href="https://bearnok.com/grva/en/knowledge/software/mathjax">MathJax</a>

In [7]:
def fx(x):
    
    m = 5
    c = 7
    
    return m*x + c

Since we declare function name as __fx__ we can call `fx()` and put some number for calculation inside `()`

In [8]:
fx(5)

32

One calling can result only an output. To calculate many numbers, we can declare multiple numbers in `[]` we call __List__. each item seperated by comma `,`

<br>

To access number in List, it arrange the index from 0 - n (item members)

In [9]:
# Learn List by fx

#idx[0,1,2,3,4,5]
X = [2,4,6,7,8,9]

call_index = 3 # in list, index 3 is 7

print(f"Value in X at index {call_index} is {X[call_index]}")

Value in X at index 3 is 7


On order to calculate outputs using `fx` function for all items in List, we can use `for ... in ... :` for looping each item in a list

Additionally, we can declare empty List `Y` to store each output of each item.

In [10]:
Y = [] # create empty list

for each_x in X: # loop over each item
    
    y = fx(each_x) # calculate item output as y
    
    Y.append(y) # add this output in Y List
    
print(f"Result list: {Y}") # Print Y List

Result list: [17, 27, 37, 42, 47, 52]


For more information, python can do inline for loop that declare `[funcx(item) for item in list]`. It result list of outputs from `fx` function within a list variable

In [11]:
[fx(x) for x in X]

[17, 27, 37, 42, 47, 52]

Then, suppose we want to keep only even number in the result. we can add `if ... else...` statement to control the flow

In [12]:
Y = [] # create empty list

for each_x in X: # loop over each item
    
    y = fx(each_x) # calculate item output as y
    
    if y % 2 == 0: # check that y is modulus 2 not equal to 0 (is even)
        continue # if yes, skip this for loop item -> go to next item
    else: # if not even number
        Y.append(y) # add this output in Y List
    
print(f"Result list: {Y}") # Print Y List

Result list: [17, 27, 37, 47]


Suppose we have more functions to do calculations, we can put the funtion calling in another fuinction calling. For example, declare another function named `gx`

In [13]:
def gx(x):
    
    m = 2
    c = 11
    
    return m*x + c

Normally, we call `fx` to calculate a number. This time we will call `gx` over `fx` again to let `gx` use the result from `fx` as an input

In [14]:
gx(fx(3))

55

which equal to this math explanation

$$
fx(x) = 5x + 7
$$

$$
22 = 5(3) + 7
$$

Then

$$
gx(x) = 2x + 11
$$

$$
55 = 2(22) + 11
$$


In [15]:
# Other tuple variables

some_tuple = (99, gx(2), fx, "string in tuple")

In [16]:
print(some_tuple[0])
print(some_tuple[1])
print(some_tuple[2])
print(some_tuple[3])

99
15
<function fx at 0x10dc36830>
string in tuple


In [56]:
some_dict = {"key1": "value1",
             "random_number": 77,
             101: "Roi-Et"}


print(some_dict['key1'])
print(some_dict['random_number'])
print(some_dict[101])

value1
77
Roi-Et


In [18]:
# Energy conservation rule

#energy = 1/2*mv^2 + mgh

m = 20 # kg
v = 5 # m/sec
g = 9.8 # m/v/v
h = 7 # m

# energy? 

In [19]:
def calc_energy(???):
    
    ...
    
    return ???


SyntaxError: invalid syntax (978393171.py, line 1)

In [20]:
print(f'Energy is: {calc_energy(???)} KJ')

SyntaxError: f-string: invalid syntax (1096267716.py, line 1)

In [21]:
countries = ['Thailand', 'England', 'USA', 'Japan']

In [22]:
for country in countries:
    
    print(country)

Thailand
England
USA
Japan


In [23]:
for index, country in enumerate(countries):
    
    print(f'{country} is index {index}')

Thailand is index 0
England is index 1
USA is index 2
Japan is index 3


In [24]:
nationalities = ['Thai', 'English', 'American', 'Japanese']

In [25]:
for country, nationality in zip(countries, nationalities):
    
    print(f'people in {country} is {nationality}')

people in Thailand is Thai
people in England is English
people in USA is American
people in Japan is Japanese


## Mathematic Calculation in Linear Algebra

This helps more understanding about mathematical operations in more easier rather using straight tuple vairable when dealing with multi-dimensional data structures. For example, a dataset can have sample axis, feature axis, time sequence axis in which represent in many dimension of data

In [26]:
import numpy as np

__Algebra Basic__
<br>
- _scalar_: a single number (e.g. value) <br>
- _vector_: Sequential 1-D numbers represent direction and length of each feature (e.g. Spectral colors R G B etc.) <br>
- _matrix_: Tabular-like 2-D numbers represent values of interested object (e.g. sample, count)) <br>
- _tensor_: multi-dimensional number extensing from length and direction such as time and spatial (e.g. time, spatial window) <br>

In [27]:
scalar = 7
vector = [3, 6, 7]
matrix = [[1, 5, 0, 2],
          [8, 2, 9, 6],
          [7, 6, 3, 4]]

Scalar and Vector are simply single value and list of scalar composing more dimension of number. Matrix and 2-D representation of multi-dimensionality that we can represent in readable format.

<br>

to access the data in matrix, we call `[idx]` after the variable

In [28]:
matrix[0][1] # row 0 column 1

5

To know dimension of matrix, use `len(x)` to show length of list

In [29]:
print(len(matrix))
print(len(matrix[0]))

3
4


However, It is more difficult to read and guess the dimension of matrix. We employ `numpy` tool to convert to numpy array type variable for more capability

In [30]:
np_matrix = np.asarray(matrix)
np_matrix

array([[1, 5, 0, 2],
       [8, 2, 9, 6],
       [7, 6, 3, 4]])

This matrix represents dataset has 3 samples and 4 features

|  | f0 | f1 | f2 | f3 |
|---|---|---|---|---|
| s0 | 1 | 5 | 0 | 2 |
| s1 | 8 | 2 | 9 | 6 |
| s2 | 7 | 6 | 3 | 4 |

that more easier to access value and shape of data

In [31]:
print('value in row 0, colum 3 -> ', np_matrix[0][3])

print('shape of matrix ->' , np_matrix.shape)

value in row 0, colum 3 ->  2
shape of matrix -> (3, 4)


Linear algebra equation

$$

y = m*x +c



$$

extend to

$$
fx(x) = w_1x_1 + w_2x_2 + w_3x_3 + w_4x_4 + b
$$

or

$$
fx(x) = W^TX + b
$$

In [32]:
X = np_matrix.copy()
W = np.array([0.5, 0.7, 1.2, 0.9])
b = np.array([5])

print('X matrix: \n',X)
print('\n Weight vector: \n', W)
print('\n Bias term: \n',b)

X matrix: 
 [[1 5 0 2]
 [8 2 9 6]
 [7 6 3 4]]

 Weight vector: 
 [0.5 0.7 1.2 0.9]

 Bias term: 
 [5]


In [33]:
y = X @ W + b #  X dot W + b

y

array([10.8, 26.6, 19.9])

As mentioned above, output of vectorized operations are results of each row (samples). This is more good in case we have more samples which takes longer computation time than looping over list variables

<br><br>

Additionally, this is more advanced to create tensor which we could not illustrate in tabular form like previous. For example,

In [74]:
a = np.random.randint(low=15000, high=25000, size=(3,5,6))
a.shape

(3, 5, 6)

The shape of `a` tensor has 3-dimension that we have to rely on showing individual matrix instead of show 3D matrix

In [75]:
print(a[0], '(0, *, *)')
print(a[1], '(1, *, *)')
print(a[2], '(2, *, *)')

[[21454 19705 20638 16653 17547 23539]
 [22406 20231 16558 23626 15165 16324]
 [24998 23391 17866 24734 21808 23430]
 [16645 17968 22830 21274 15475 22683]
 [21073 18495 15771 19118 21976 21269]] (0, *, *)
[[17045 17699 20901 17608 18585 21458]
 [22193 19417 16176 17893 22960 16056]
 [21380 23249 23118 15514 18085 16638]
 [22408 20711 19067 18314 18252 23610]
 [17759 20623 18235 16747 19544 22818]] (1, *, *)
[[20896 15079 20463 18903 16011 22103]
 [20331 18445 16615 16131 20648 22212]
 [21826 24364 18128 24600 16504 18552]
 [18346 23492 19948 17851 18478 22649]
 [16240 17557 19435 17155 20250 21764]] (2, *, *)


Suppose above tensor is like satellite image which has 3 bands, 5 height, 6 width. To access a pixel at index 2,2 by every bands we can call

In [76]:
a[:, 2, 2]

array([17866, 23118, 18128])

In general calculation of satellite image, we usually use a band-level data calculation. For example band A to calculate reflectance from Digital number of data such as landsat formula

$$
Reflectance = DN * 0.0000275 - 0.2
$$

we can make the formula to be a function like

In [77]:
def reflectance_calc(x):
    
    return x * 0.0000275 - 0.2

We can write as lambda function as

In [78]:
refl_calc = lambda x: x * 0.0000275 - 0.2

to implement band-level calculation, pass the band numpy array data to the function

![image info](https://pages.cms.hu-berlin.de/EOL/geo_rs/fig/s00_array_scaling.PNG)

In [79]:
reflectance_calc(a[0])

array([[0.389985 , 0.3418875, 0.367545 , 0.2579575, 0.2825425, 0.4473225],
       [0.416165 , 0.3563525, 0.255345 , 0.449715 , 0.2170375, 0.24891  ],
       [0.487445 , 0.4432525, 0.291315 , 0.480185 , 0.39972  , 0.444325 ],
       [0.2577375, 0.29412  , 0.427825 , 0.385035 , 0.2255625, 0.4237825],
       [0.3795075, 0.3086125, 0.2337025, 0.325745 , 0.40434  , 0.3848975]])

Or use lambda function to calculate reflectance

In [80]:
refl_calc(a[0])

array([[0.389985 , 0.3418875, 0.367545 , 0.2579575, 0.2825425, 0.4473225],
       [0.416165 , 0.3563525, 0.255345 , 0.449715 , 0.2170375, 0.24891  ],
       [0.487445 , 0.4432525, 0.291315 , 0.480185 , 0.39972  , 0.444325 ],
       [0.2577375, 0.29412  , 0.427825 , 0.385035 , 0.2255625, 0.4237825],
       [0.3795075, 0.3086125, 0.2337025, 0.325745 , 0.40434  , 0.3848975]])

Same way, suppose there are 2 bands to calculate ND..I like (Normalized Difference)



In [81]:
(a[0] - a[1]) / (a[0] + a[1])

array([[ 0.11452246,  0.05363063, -0.0063314 , -0.02787426, -0.028728  ,
         0.04624753],
       [ 0.00477589,  0.02053067,  0.01166982,  0.13808136, -0.20445902,
         0.00827671],
       [ 0.07801113,  0.0030446 , -0.12814757,  0.22907971,  0.09332464,
         0.16951183],
       [-0.14756869, -0.07091704,  0.0898155 ,  0.07477013, -0.08233759,
        -0.02002463],
       [ 0.08534199, -0.05439951, -0.0724578 ,  0.06610902,  0.05857418,
        -0.03513507]])

This is a basic of raster calculation using numpy by matrix (or tensor) data math. Next section is to actual raster data exploration and some Machine Learning part