<h1 style="text-align:center;">Workshop Training</h1> 

<h2 style="text-align:center;">LULC Analysis and Classification using Remote Sensing Data with Machine Learning Approach</h2> 

### Section 1: Python CrashCourse

Run first python code by press Shift+Enter

In [1]:
print("First Python Run!!")

First Python Run!!


We can document the code to explain what the code does and explain some theory about the code

__Double Click Me!!__ 

Try to Write Markdown Here

You can write _Italic_, __bold__, <span style="color:blue">*Colored*</span>.

Markdown text describing something including ภาษาไทย

# Defining Heading 1
## Defining Heading 2
### Defining Heading 3

- List 1
- List 2
  - List 2.1


Write somthing here...

Latest cell ran single text string to show in output. Now, declare a variable to store some text inside and print it using variable names.

In [3]:
print("This is a string data") # print simple string

some_string = "This is another string data" # store text in variable
some_number = 345 # store number in variable

print(some_string) # print data in string variable

print(some_number) # print data in number variable

This is a string data
This is another string data
345


To print out message including mixing text and number, there are several ways

In [4]:
print("This is a string data" + " and another string data") # concat string by +

print("Print by normal message", some_number, some_string) # concat message by comma -> x,y,z,..

print(f"Print by format string message {some_number} with {some_number}") # format printting using {x} to show data in blacket placement


This is a string data and another string data
Print by normal message 345 This is another string data
Print by format string message 345 with 345


Explore some simple programmatically math calculations to explore __Arithmetic Operation__

In [5]:
print('General Operator')

# General Arithmetic Operators
print(2+3) # Add
print(5-1) # Subtract
print(5*4) # Multiply
print(18/4) # Divide

print('\nAdditional Operator')

# Addditional Arithmetic Operators
print(10//3) # Floor division
print(10%3) # Modulus
print(4**2) # Expotentiation (Power)

General Operator
5
4
20
4.5

Additional Operator
3
1
16


Do some math calculation using those arithmetic operators by math equation

$$
 y = f(x)
$$

$$
 f(x) = mx +c
$$

$$
y = 3x + 1
$$

In [43]:
# Learn Variables by Linear Algebra

# y = mx+c

m = 3
c = 1

x = 5

y = m * x +c

print(f"The y is: {y}")

The y is: 16


You may know what Fx (Function) in math. Now, try to create a function doing calculation that equation. We do same way as declaring a variable and put the formula like

$$
  f(x) = 5x + 7
$$

explore how to write Latex formula at <a href="https://bearnok.com/grva/en/knowledge/software/mathjax">MathJax</a>

In [44]:
def f(x):
    
    m = 5
    c = 7
    
    return m*x + c

Since we declare function name as __f__ we can call `f()` and put some number for calculation inside `()`

In [45]:
f(5)

32

One calling can result only an output. To calculate many numbers, we can declare multiple numbers in `[]` we call __List__. each item seperated by comma `,`

<br>

To access number in List, it arrange the index from 0 - n (item members)

In [46]:
# Learn List by fx

#idx[0,1,2,3,4,5]
X = [2,4,6,7,8,9]

call_index = 3 # in list, index 3 is 7

print(f"Value in X at index {call_index} is {X[call_index]}")

Value in X at index 3 is 7


On order to calculate outputs using `f` function for all items in List, we can use `for ... in ... :` for looping each item in a list

Additionally, we can declare empty List `Y` to store each output of each item.

In [47]:
Y = [] # create empty list

for each_x in X: # loop over each item
    
    y = f(each_x) # calculate item output as y
    
    Y.append(y) # add this output in Y List
    
print(f"Result list: {Y}") # Print Y List

Result list: [17, 27, 37, 42, 47, 52]


For more information, python can do inline for loop that declare `[funcx(item) for item in list]`. It result list of outputs from `fx` function within a list variable

In [48]:
[f(x) for x in X]

[17, 27, 37, 42, 47, 52]

Then, suppose we want to keep only even number in the result. we can add `if ... else...` statement to control the flow

In [49]:
Y = [] # create empty list

for each_x in X: # loop over each item
    
    y = f(each_x) # calculate item output as y
    
    if y % 2 == 0: # check that y is modulus 2 not equal to 0 (is even)
        continue # if yes, skip this for loop item -> go to next item
    else: # if not even number
        Y.append(y) # add this output in Y List
    
print(f"Result list: {Y}") # Print Y List

Result list: [17, 27, 37, 47]


Suppose we have more functions to do calculations, we can put the funtion calling in another fuinction calling. For example, declare another function named `g`

In [50]:
def g(x):
    
    m = 2
    c = 11
    
    return m*x + c

Normally, we call `fx` to calculate a number. This time we will call `g` over `f` again to let `g` use the result from `f` as an input

In [53]:
g(f(3))

55

which equal to this math explanation

$$
f(x) = 5x + 7
$$

$$
22 = 5(3) + 7
$$

Then

$$
g(x) = 2x + 11
$$

$$
55 = 2(22) + 11
$$


### Tuple

Tuple vairable is like list of vairable items which are immutable (only assign, no change) capsuleted by `()`. Usually used for constant variables decalration

In [54]:
# Other tuple variables

some_tuple = (99, g(2), f, "string in tuple")

Access item as well as list

In [55]:
print(some_tuple[0])
print(some_tuple[1])
print(some_tuple[2])
print(some_tuple[3])

99
15
<function f at 0x1199b9870>
string in tuple


### Dictionary

Dictionary is JSON like varable which has _key_ and _value_. We can have nested dictionaries mixed with various types of items, generic, list, tuple, dict even function.

In [64]:
some_dict = {"key1": "value1",
             "random_number": 77,
             101: "Roi-Et"}


print(some_dict['key1'])
print(some_dict['random_number'])
print(some_dict[101])

value1
77
Roi-Et


## Excercise

We familiarize the general python coding and some mathematical operations. Here is an exercise to calculate physics formula by function as fast quiz

Given Energy conservation eqaution (Mechanical Energy) from Kinetic Energy and Potential energy

$$
ME = \frac{1}{2}mv^2 +mgh
$$

In [67]:
# Energy conservation rule

#energy = 1/2*mv^2 + mgh

m = 20 # kg
v = 5 # m/sec
g = 9.8 # m/v/v
h = 7 # m

# energy? 

Make a function

In [ ]:
def calc_energy(???):
    
    # Code here
    
    return ???


Test your function

In [ ]:
# print(f'Energy is: {???} J')

Energy is: 1622.0 KJ


## Loop over sequence variables

In [69]:
countries = ['Thailand', 'England', 'USA', 'Japan']

For loop

In [70]:
for country in countries:
    
    print(country)

Thailand
England
USA
Japan


`enumerate` will extract the idx of item with item at a time of generator

In [77]:
for index, country in enumerate(countries):
    
    print(f'{country} is index {index}')

Thailand is index 0
England is index 1
USA is index 2
Japan is index 3


Suppose we have another list

In [78]:
nationalities = ['Thai', 'English', 'American', 'Japanese']

`zip` bundles together the two or more list to extract at a time of generator

In [79]:
for country, nationality in zip(countries, nationalities):
    
    print(f'people in {country} is {nationality}')

people in Thailand is Thai
people in England is English
people in USA is American
people in Japan is Japanese


## Mathematic Calculation in Linear Algebra

This helps more understanding about mathematical operations in more easier rather using straight tuple vairable when dealing with multi-dimensional data structures. For example, a dataset can have sample axis, feature axis, time sequence axis in which represent in many dimension of data

In [81]:
import numpy as np

np.set_printoptions(suppress=True, precision=3)

__Algebra Basic__
<br>
- _scalar_: a single number (e.g. value) <br>
- _vector_: Sequential 1-D numbers represent direction and length of each feature (e.g. Spectral colors R G B etc.) <br>
- _matrix_: Tabular-like 2-D numbers represent values of interested object (e.g. sample, count)) <br>
- _tensor_: multi-dimensional number extensing from length and direction such as time and spatial (e.g. time, spatial window) <br>

![](https://miro.medium.com/v2/resize:fit:1008/1*tN5uOe_VdzFcNpRcYFeMqQ.jpeg)

In [82]:
scalar = 7
vector = [3, 6, 7]
matrix = [[1, 5, 0, 2],
          [8, 2, 9, 6],
          [7, 6, 3, 4]]

Scalar and Vector are simply single value and list of scalar composing more dimension of number. Matrix and 2-D representation of multi-dimensionality that we can represent in readable format.

<br>

to access the data in matrix, we call `[idx]` after the variable

In [84]:
matrix[0][1] # row 0 column 1

5

To know dimension of matrix, use `len(x)` to show length of list

In [85]:
print(len(matrix))
print(len(matrix[0]))

3
4


However, It is more difficult to read and guess the dimension of matrix. We employ `numpy` tool to convert to numpy array type variable for more capability

In [87]:
np_matrix = np.asarray(matrix)
np_matrix

array([[1, 5, 0, 2],
       [8, 2, 9, 6],
       [7, 6, 3, 4]])

This matrix represents dataset has 3 samples and 4 features

|  | f0 | f1 | f2 | f3 |
|---|---|---|---|---|
| s0 | 1 | 5 | 0 | 2 |
| s1 | 8 | 2 | 9 | 6 |
| s2 | 7 | 6 | 3 | 4 |

that more easier to access value and shape of data

In [90]:
print('value in row 0, colum 3 -> ', np_matrix[0, 3])

print('shape of matrix ->' , np_matrix.shape)

value in row 0, colum 3 ->  2
shape of matrix -> (3, 4)


Linear algebra equation

$$

y = m*x +c



$$

extend to

$$
f(x) = w_1x_1 + w_2x_2 + w_3x_3 + w_4x_4 + w_nx_n + b
$$

or

$$
f(x) = W^TX + b
$$

in ML ways we usally use this to show in hypothesis function

$$
h_\theta(x) = \theta_0 + \theta_1x
$$

All are same thing referring to linear algebra


In [94]:
X = np_matrix.copy()
W = np.array([0.5, 0.7, 1.2, 0.9])
b = np.array([5])

print('X matrix: \n',X)
print('\n theta vector: \n', W)
print('\n bias term: \n',b)

X matrix: 
 [[1 5 0 2]
 [8 2 9 6]
 [7 6 3 4]]

 theta vector: 
 [0.5 0.7 1.2 0.9]

 bias term: 
 [5]



![](https://lh3.googleusercontent.com/ThNU3UAuMF1OBCxP4TkVf5kwrs88bb4ncH1-KQgv69_1Mw_rBfgKYDG1f8XsOWMSRmaapKFMvHFMDAFh1GmlMBw3uA9307Yk8fxMe9s4CriMyqtvrZLoQB1LMAAbQLbDKgY5P3Gt)

In [95]:
y = X @ W + b #  X dot W + b, equal to np.matmul(X, W) +b

y

array([10.8, 26.6, 19.9])

In [98]:
np.dot(X, W) + b

array([10.8, 26.6, 19.9])

In [99]:
np.matmul(X, W) + b

array([10.8, 26.6, 19.9])

As mentioned above, output of vectorized operations are results of each row (samples). This is more good in case we have more samples which takes longer computation time than looping over list variables

<br><br>

## Tensor

Additionally, this is more advanced to create tensor which we could not illustrate in tabular form like previous. For example,

In [100]:
a = np.random.randint(low=15000, high=25000, size=(3,5,6))
a.shape

(3, 5, 6)

The shape of `a` tensor has 3-dimension that we have to rely on showing individual matrix instead of show 3D matrix

In [101]:
print(a[0], '(0, *, *)')
print(a[1], '(1, *, *)')
print(a[2], '(2, *, *)')

[[20633 24846 21433 16924 15155 21577]
 [20156 22132 23641 19430 23199 20749]
 [15704 24894 22118 21711 21607 22691]
 [20722 23413 22484 21306 23846 19572]
 [17669 16952 24582 18910 24658 17383]] (0, *, *)
[[21359 18635 21597 16945 16512 20627]
 [15900 19489 15062 20093 22919 15065]
 [16099 21211 23832 17930 21038 21198]
 [21762 24070 19140 21253 19552 18495]
 [18360 19664 15361 21788 18041 15563]] (1, *, *)
[[16263 18830 16454 18084 17942 17215]
 [23083 19186 24650 16511 19682 22444]
 [23534 24539 19771 18930 19688 20876]
 [22929 24911 22727 17692 16535 23361]
 [18790 22410 19005 22441 19175 20898]] (2, *, *)


Suppose above tensor is like satellite image which has 3 bands, 5 height, 6 width. To access a pixel at index 2,2 by every bands we can call

In [102]:
a[:, 2, 2]

array([22118, 23832, 19771])

In general calculation of satellite image, we usually use a band-level data calculation. For example band A to calculate reflectance from Digital number of data such as landsat formula

$$
Reflectance = DN * 0.0000275 - 0.2
$$

we can make the formula to be a function like

In [103]:
def reflectance_calc(x):
    
    return x * 0.0000275 - 0.2

We can write as lambda function as

In [104]:
refl_calc = lambda x: x * 0.0000275 - 0.2

to implement band-level calculation, pass the band numpy array data to the function

![](https://pages.cms.hu-berlin.de/EOL/geo_rs/fig/s00_array_scaling.png)

In [105]:
reflectance_calc(a[0])

array([[0.367, 0.483, 0.389, 0.265, 0.217, 0.393],
       [0.354, 0.409, 0.45 , 0.334, 0.438, 0.371],
       [0.232, 0.485, 0.408, 0.397, 0.394, 0.424],
       [0.37 , 0.444, 0.418, 0.386, 0.456, 0.338],
       [0.286, 0.266, 0.476, 0.32 , 0.478, 0.278]])

Or use lambda function to calculate reflectance

In [106]:
refl_calc(a[0])

array([[0.367, 0.483, 0.389, 0.265, 0.217, 0.393],
       [0.354, 0.409, 0.45 , 0.334, 0.438, 0.371],
       [0.232, 0.485, 0.408, 0.397, 0.394, 0.424],
       [0.37 , 0.444, 0.418, 0.386, 0.456, 0.338],
       [0.286, 0.266, 0.476, 0.32 , 0.478, 0.278]])

Same way, suppose there are 2 bands to calculate ND..I like (Normalized Difference)



In [107]:
(a[0] - a[1]) / (a[0] + a[1])

array([[-0.017,  0.143, -0.004, -0.001, -0.043,  0.023],
       [ 0.118,  0.064,  0.222, -0.017,  0.006,  0.159],
       [-0.012,  0.08 , -0.037,  0.095,  0.013,  0.034],
       [-0.024, -0.014,  0.08 ,  0.001,  0.099,  0.028],
       [-0.019, -0.074,  0.231, -0.071,  0.155,  0.055]])

This is a basic of raster calculation using numpy by matrix (or tensor) data math.

This actually should be in first part of the workshop, but it is good for learning about what are we doing first. This is essential lesson for remote sensing analysis; Data Type. We works with numeric data, so we could not avoid this to optimize solution for better usage

In [162]:
import sys

print(f'Data typr is', a.dtype)
print(f'Comsume memmory', a.nbytes, ' Bytes')

Data typr is int64
Comsume memmory 720  Bytes


Why int64?. we use `itemsize` to show size of an item in Bytes. It shows 8 bytes, and each byte has 8-bits. It therefore 8x8 = 64-bits number 

In [163]:
item_byte = a.itemsize # 8
item_bits = a.itemsize * 8 # 1 byte = 8 bits

print(f' a tensor has memory size in each item {item_byte} bytes which is {item_bits} bits')

 a tensor has memory size in each item 8 bytes which is 64 bits


we know that each item is 8 bytes size with 90 items

In [ ]:
print(a.shape)
print(3 * 5 * 6)

print(f'a tensor has {a.size} items')

(3, 5, 6)
90
a tensor has 90


It takes memory for

In [139]:
print(f'a tensor consume {a.size * a.itemsize} bytes for data')

a tensor consume 720 bytes for data


Or

In [140]:
a.nbytes

720

Nevertheless, actual memory size takes

In [ ]:
a.__sizeof__()

864

This is explanation

In [147]:
a

array([[[20633, 24846, 21433, 16924, 15155, 21577],
        [20156, 22132, 23641, 19430, 23199, 20749],
        [15704, 24894, 22118, 21711, 21607, 22691],
        [20722, 23413, 22484, 21306, 23846, 19572],
        [17669, 16952, 24582, 18910, 24658, 17383]],

       [[21359, 18635, 21597, 16945, 16512, 20627],
        [15900, 19489, 15062, 20093, 22919, 15065],
        [16099, 21211, 23832, 17930, 21038, 21198],
        [21762, 24070, 19140, 21253, 19552, 18495],
        [18360, 19664, 15361, 21788, 18041, 15563]],

       [[16263, 18830, 16454, 18084, 17942, 17215],
        [23083, 19186, 24650, 16511, 19682, 22444],
        [23534, 24539, 19771, 18930, 19688, 20876],
        [22929, 24911, 22727, 17692, 16535, 23361],
        [18790, 22410, 19005, 22441, 19175, 20898]]])

Examine this, we have an array of 6 items, 5 arrays, 3 bands. each of array must have a pointer as reference index to rows and bands. So we need 8 pointers. The thing is each of pointer of `int64` need 8 bytes or 64-bits __Computer OS 64-bits__, then 144 bytes are reserved for those pointers

In [149]:
a.__sizeof__() - a.nbytes

144

What are learn from this is data type is important to memory allocation for raster. as large as data type requires more memory even computational resource to store, load, process, and save.

We can convert the data type to something like `uint16` which smaller `4X` times

In [155]:
a_16 = a.astype(np.uint16)

print(a_16)

print(a_16.nbytes, a_16.__sizeof__())

[[[20633 24846 21433 16924 15155 21577]
  [20156 22132 23641 19430 23199 20749]
  [15704 24894 22118 21711 21607 22691]
  [20722 23413 22484 21306 23846 19572]
  [17669 16952 24582 18910 24658 17383]]

 [[21359 18635 21597 16945 16512 20627]
  [15900 19489 15062 20093 22919 15065]
  [16099 21211 23832 17930 21038 21198]
  [21762 24070 19140 21253 19552 18495]
  [18360 19664 15361 21788 18041 15563]]

 [[16263 18830 16454 18084 17942 17215]
  [23083 19186 24650 16511 19682 22444]
  [23534 24539 19771 18930 19688 20876]
  [22929 24911 22727 17692 16535 23361]
  [18790 22410 19005 22441 19175 20898]]]
180 324


If we are not be careful, it accidentally assign as `float128`, it takes `2X` memory than `int64`

In [157]:
a_128 = a.astype(np.float128)

print(a_128)

print(a_128.nbytes, a_128.__sizeof__())

[[[20633. 24846. 21433. 16924. 15155. 21577.]
  [20156. 22132. 23641. 19430. 23199. 20749.]
  [15704. 24894. 22118. 21711. 21607. 22691.]
  [20722. 23413. 22484. 21306. 23846. 19572.]
  [17669. 16952. 24582. 18910. 24658. 17383.]]

 [[21359. 18635. 21597. 16945. 16512. 20627.]
  [15900. 19489. 15062. 20093. 22919. 15065.]
  [16099. 21211. 23832. 17930. 21038. 21198.]
  [21762. 24070. 19140. 21253. 19552. 18495.]
  [18360. 19664. 15361. 21788. 18041. 15563.]]

 [[16263. 18830. 16454. 18084. 17942. 17215.]
  [23083. 19186. 24650. 16511. 19682. 22444.]
  [23534. 24539. 19771. 18930. 19688. 20876.]
  [22929. 24911. 22727. 17692. 16535. 23361.]
  [18790. 22410. 19005. 22441. 19175. 20898.]]]
1440 1584
